
# Tcl/Expect code for the FreeForm server tests.
# 
# $Id: unix.exp,v 1.2 1999/05/24 22:06:18 jimg Exp $

set version {ff/3.0.0a}

# Read the common code for tests.

if {[info exists env(DODS_ROOT)] && [file exists $env(DODS_ROOT)/etc/common_tests.exp]} {
    source $env(DODS_ROOT)/etc/common_tests.exp
} elseif {[file exists ../../etc/common_tests.exp]} {
    source ../../etc/common_tests.exp
} else {
    send_user "Could not load common tests!"
    exit(1)
}

# The four `required' procs are _start, _load, _exit and _version.

proc ff_das_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing ff_das -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ff_das -v $version $args" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing ff_das -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ff_das -v $version $args >& $file" comp_output
    }
}

proc ff_das_load {} {
}

proc ff_das_exit {} {
    send -raw ""
}

proc ff_das_version {} {
    send_user "ff_das test suite 1.0\n"
}

proc ff_dds_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing ff_dds -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ff_dds -v $version $args" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing ff_dds -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ff_dds -v $version $args >& $file" comp_output
    }
}

proc ff_dds_load {} {
}

proc ff_dds_exit {} {
    send -raw ""
}

proc ff_dds_version {} {
    send_user "ff_dds test suite 1.0\n"
}

proc ff_dods_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing ff_dods -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ff_dods -v $version $args" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing ff_dods -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ff_dods -v $version $args >& $file" comp_output
    }
}

proc ff_dods_load {} {
}

proc ff_dods_exit {} {
    send -raw ""
}

proc ff_dods_version {} {
    send_user "ff_dods test suite 1.0\n"
}
