#
# $Id: das.1.exp,v 1.1 2003/05/14 18:15:06 jimg Exp $

global comp_output		# contains output from ff_das_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "ff-test/test-files.tcl"

set test_name "DAS Tests"

# The `1' in compare_stdout means call xfail if the test fails.

ff_das_start $avhrr
compare_stdout $avhrr_das "$test_name: avhrr" 0 "match"

ff_das_start $jplpath
compare_stdout $jplpath_das "$test_name: jplpath" 0 "match"

ff_das_start $test0
compare_stdout $test0_das "$test_name: test0" 0 "match"

ff_das_start $test1
compare_stdout $test1_das "$test_name: test1" 0 "match"

#  ff_das_start $test2
#  compare_stdout $test2_das "$test_name: test2" 0 "match"

#  ff_das_start $test3
#  compare_stdout $test3_das "$test_name: test3" 0 "match"

ff_das_start $test4
compare_stdout $test4_das "$test_name: test4" 0 "match"

ff_das_start $test5
compare_stdout $test5_das "$test_name: test5" 0 "match"

ff_das_start $test6
compare_stdout $test6_das "$test_name: test6" 0 "match"

ff_das_start $test7
compare_stdout $test7_das "$test_name: test7" 0 "match"

ff_das_start $test8
compare_stdout $test8_das "$test_name: test8" 0 "match"

ff_das_start $test9
compare_stdout $test9_das "$test_name: test9" 0 "match"

#  ff_das_start $test10
#  compare_stdout $test10_das "$test_name: test10" 0 "match"

ff_das_start $t3
compare_stdout $t3_das "$test_name: t3" 0 "match"


