
#
# $Id: date_time.1.exp,v 1.1 2003/05/14 18:15:06 jimg Exp $
#
# Tests for the date/time interface.

global comp_output		# contains output from ff_dods_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "ff-test/test-files.tcl"

set test_name "Time Interface Tests"

# The `1' in compare_stdout means call xfail if the test fails.

# Test the Date_Time interface.

# Single argument to date_time()
ff_dods_start "$avhrr -e DODS_URL&date_time(\"1998/160:17:45:00\")"
compare_stdout "ff-test/avhrr_date_time_ce1.bin" "$test_name: Single date/time" 0 "match"

# Two arguments to date_time()
ff_dods_start "$avhrr -e DODS_URL&date_time(\"1998/160:17:00:00\",\"1998/160:18:00:00\")"
compare_stdout "ff-test/avhrr_date_time_ce2.bin" "$test_name: Date/Time range" 0 "match"


# Return values from DODS_Date_Time()
ff_dods_start "$avhrr -e DODS_URL,DODS_Date_Time(GSO_AVHRR)&date_time(\"1998/160:17:00:00\",\"1998/160:18:00:00\")"
compare_stdout "ff-test/avhrr_date_time_ce3.bin" "$test_name: Date_Time(...) return" 0 "match"

# Check bad syntax to the projection functions DODS_Date_Time()

ff_dods_start "$avhrr -e DODS_URL,DODS_Date_Time(GSO_AVHR)&date_time(\"1998/160:14:45:00\")"
compare_stdout "ff-test/avhrr_date_time_err1.txt" "$test_name: Misspelled variable name to DODS_Date_Time()" 1 "match"

# Use types other than int32 in the .fmt file.
ff_dods_start "$avhrr_t1 -e DODS_URL&date_time(\"1998/160:17:45:00\")"
compare_stdout "ff-test/avhrr_date_time_ce1.bin" "$test_name: Non-int32 types in the format file for times" 0 "match"

# Use types other than int32 in the .fmt file.
ff_dods_start "$avhrr_t2 -e DODS_URL&date_time(\"1998/160:17:45:00\")"
compare_stdout "ff-test/avhrr_date_time_ce1.bin" "$test_name: Non-int32 types in the format file for dates" 0 "match"








