#
# $Id: dds.1.exp,v 1.1 2003/05/14 18:15:06 jimg Exp $

global comp_output		# contains output from ff_dds_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "ff-test/test-files.tcl"

set test_name "DDS Tests"

# The `1' in compare_stdout means call xfail if the test fails.

ff_dds_start $avhrr
compare_stdout $avhrr_dds "$test_name: avhrr" 0 "match"

ff_dds_start $jplpath
compare_stdout $jplpath_dds "$test_name: jplpath" 0 "match"

ff_dds_start $test0
compare_stdout $test0_dds "$test_name: test0" 0 "match"

ff_dds_start $test1
compare_stdout $test1_dds "$test_name: test1" 0 "match"

#  ff_dds_start $test2
#  compare_stdout $test2_dds "$test_name: test2" 0 "match"

#  ff_dds_start $test3
#  compare_stdout $test3_dds "$test_name: test3" 0 "match"

ff_dds_start $test4
compare_stdout $test4_dds "$test_name: test4" 0 "match"

ff_dds_start $test5
compare_stdout $test5_dds "$test_name: test5" 0 "match"

ff_dds_start $test6
compare_stdout $test6_dds "$test_name: test6" 0 "match"

ff_dds_start $test7
compare_stdout $test7_dds "$test_name: test7" 0 "match"

ff_dds_start $test8
compare_stdout $test8_dds "$test_name: test8" 0 "match"

ff_dds_start $test9
compare_stdout $test9_dds "$test_name: test9" 0 "match"

#  ff_dds_start $test10
#  compare_stdout $test10_dds "$test_name: test10" 0 "match"

ff_dds_start $t3
compare_stdout $t3_dds "$test_name: t3" 0 "match"

ff_dds_start $dbl_data
compare_stdout $dbl_data.dds.txt "$test_name: dbl_data" 0 "match"

ff_dds_start $dbl_data3
compare_stdout $dbl_data3.dds.txt "$test_name: dbl_data3" 0 "match"


