
# Tcl/Expect code for the FreeForm server tests.
# 
# $Id$

set version {ff/3.5.0}

global GETDAP
if ![info exists GETDAP] then {
    set GETDAP [transform getdap]
}

# Read the common code for tests.

if {[file exists common_tests.exp]} {
    source common_tests.exp
} else {
    send_user "Could not load common tests!"
    exit(1)
}

# The four `required' procs are _start, _load, _exit and _version.

proc ff_das_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o das -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o das -v $version $args" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o das -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o das -v $version $args >& $file" comp_output
    }
}

proc ff_das_load {} {
}

proc ff_das_exit {} {
    send -raw ""
}

proc ff_das_version {} {
    send_user "ff_handler -o das test suite 1.0\n"
}

proc ff_dds_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o dds -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o dds -v $version $args" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o dds -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o dds -v $version $args >& $file" comp_output
    }
}

proc ff_dds_load {} {
}

proc ff_dds_exit {} {
    send -raw ""
}

proc ff_dds_version {} {
    send_user "dap_ff_handler -o dds test suite 1.0\n"
}

proc ff_dods_start { {args ""} {file ""}} {
    global verbose
    global comp_output
    global spawn_id
    global version
    global GETDAP

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o dods -v $version $args ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o dods -v $version $args | $GETDAP -s -" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing dap_ff_handler -o dods -v $version $args >& $file ...\n"
	    exp_internal 1
	}
	catch "exec ./dap_ff_handler -o dods -v $version $args >& $file | $GETDAP -s -" comp_output
    }
}

proc ff_dods_load {} {
}

proc ff_dods_exit {} {
    send -raw ""
}

proc ff_dods_version {} {
    send_user "dap_ff_handler -o dods test suite 1.0\n"
}
